# Generated by Django 3.2.7 on 2021-11-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('numerospag', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Ficcion', 'ficcion'), ('Biografica', 'biografica'), ('Ciencia', 'ciencia'), ('Dramatico', 'dramatico'), ('Accion', 'accion'), ('Clasica', 'clasica')], max_length=10)),
            ],
        ),
    ]
